import {useRef,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {ScrollView,Text,TextInput,Pressable,View,Modal} from 'react-native';
import {CameraView,useCameraPermissions} from 'expo-camera';
import {apiFetch,asList} from '../../src/api/client';
import {cachedRead} from '../../src/sync/db';
import {submitQueued} from '../../src/sync/engine';
import {useAuth} from '../../src/auth/AuthContext';
import {Card,Pill,useStyles} from '../../src/ui';
type Asset={id:string;asset_code:string;serial_number?:string;name:string;status:string;condition:string;version:number};
type Employee={id:string;name:string};
const edges:Record<string,string[]>={AVAILABLE:['DAMAGED','LOST'],ASSIGNED:['IN_USE','RETURNED','DAMAGED','LOST'],IN_USE:['RETURNED','DAMAGED','LOST'],RETURNED:['AVAILABLE','DAMAGED'],DAMAGED:['AVAILABLE','WRITTEN_OFF'],LOST:['RETURNED','WRITTEN_OFF']};
export default function Assets(){
 const S=useStyles(),{canDo}=useAuth(),[search,setSearch]=useState(''),[selected,setSelected]=useState<Asset|null>(null),[scanning,setScanning]=useState(false),[permission,ask]=useCameraPermissions(),[condition,setCondition]=useState('GOOD'),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),scanBusy=useRef(false);
 const [employee,setEmployee]=useState(''),[employeeSearch,setEmployeeSearch]=useState(''),[audit,setAudit]=useState(false),[auditName,setAuditName]=useState(''),[expected,setExpected]=useState<string[]>([]),[scans,setScans]=useState<Record<string,string>>({});
 const assets=useQuery({queryKey:['assets'],queryFn:()=>cachedRead('assets',async()=>asList<Asset>((await apiFetch('/api/v1/assets?limit=100')).data)),enabled:canDo('asset.read')});
 const employees=useQuery({queryKey:['asset-employees'],queryFn:()=>cachedRead('asset-employees',async()=>asList<Employee>((await apiFetch('/api/v1/assets/eligible-employees')).data)),enabled:canDo('asset.manage')});
 const filtered=assets.data?.filter(a=>`${a.name} ${a.asset_code}`.toLowerCase().includes(search.toLowerCase()))??[];
 const pick=(a:Asset)=>{setSelected(a);setCondition(a.condition);setMessage('');};
 async function scan(code:string){if(scanBusy.current)return;scanBusy.current=true;setScanning(false);try{
  let asset=assets.data?.find(a=>a.asset_code===code||a.serial_number===code);
  if(!asset){const {data}=await apiFetch<{id:string}>(`/api/v1/assets/resolve?code=${encodeURIComponent(code)}`);asset=(await apiFetch<Asset>(`/api/v1/assets/${data.id}`)).data;}
  if(audit)setScans(old=>({...old,[asset!.id]:condition}));else pick(asset);
 }catch(e){setMessage(e instanceof Error?e.message:'Asset not found. Uncached assets require a connection.');}finally{scanBusy.current=false;}}
 async function queue(entity:'asset_transition'|'asset_assignment'|'asset_audit',payload:Record<string,unknown>){setBusy(true);setMessage('');try{setMessage(await submitQueued({entity,op:`${entity}:${selected?.id??auditName}:${Date.now()}`,payload,baseVersion:entity==='asset_audit'?undefined:selected?.version}));await assets.refetch();if(entity==='asset_audit'){setAudit(false);setExpected([]);setScans({});}else setSelected(null);}catch(e){setMessage(e instanceof Error?e.message:'Could not save');}finally{setBusy(false);}}
 const openScanner=async()=>{if(!permission?.granted&&!(await ask()).granted){setMessage('Camera permission is required to scan.');return;}setScanning(true);};
 if(!canDo('asset.read'))return <View style={S.screen}><Text style={S.body}>Your role does not have asset access.</Text></View>;
 return <ScrollView style={S.screen}><Text style={S.h1}>Assets</Text><TextInput style={S.input} accessibilityLabel="Search assets" placeholder="Search cached assets" value={search} onChangeText={setSearch}/><Pressable style={S.btn} onPress={()=>void openScanner()}><Text style={S.btnText}>{audit?'Scan observed asset':'Scan QR or barcode'}</Text></Pressable>
 {canDo('asset.manage')?<Pressable style={S.btnGhost} onPress={()=>setAudit(v=>!v)}><Text style={S.btnGhostText}>{audit?'Close audit draft':'Start physical audit'}</Text></Pressable>:null}
 {message?<Text accessibilityRole="alert" style={S.body}>{message}</Text>:null}{assets.error?<Text style={S.error}>{assets.error.message}</Text>:null}
 {audit?<Card title="Physical audit"><TextInput style={S.input} placeholder="Audit name" value={auditName} onChangeText={setAuditName}/><TextInput style={S.input} placeholder="Observed condition for next scan" value={condition} onChangeText={setCondition}/><Text style={S.muted}>Select the expected assets below, then scan those present. Expected assets without a scan are missing. Cached assets can be scanned offline.</Text>{Object.entries(scans).map(([id,c])=><Pressable key={id} onPress={()=>setScans(old=>{const next={...old};delete next[id];return next;})}><Text style={S.body}>{assets.data?.find(a=>a.id===id)?.asset_code??id} · {c} · Remove scan</Text></Pressable>)}<Pressable disabled={busy||!auditName.trim()||!expected.length} style={S.btn} onPress={()=>void queue('asset_audit',{name:auditName.trim(),expected_ids:expected,scans:Object.entries(scans).map(([asset_id,condition])=>({asset_id,condition}))})}><Text style={S.btnText}>Complete audit</Text></Pressable></Card>:null}
 {filtered.map(a=><Pressable key={a.id} onPress={()=>audit?setExpected(ids=>ids.includes(a.id)?ids.filter(id=>id!==a.id):[...ids,a.id]):pick(a)}><Card title={(audit?(expected.includes(a.id)?'✓ ':'○ '):'')+a.name}><Text style={S.muted}>{a.asset_code} · {a.condition}</Text><Pill text={a.status} tone="info"/></Card></Pressable>)}{!filtered.length?<Text style={S.muted}>No cached assets match. Refresh while online to update the register.</Text>:null}
 {selected&&!audit?<Card title={selected.name}><Text style={S.body}>{selected.asset_code} · {selected.status}</Text>{canDo('asset.manage')?<><TextInput style={S.input} accessibilityLabel="Condition" placeholder="Condition" value={condition} onChangeText={setCondition}/><TextInput style={S.input} accessibilityLabel="Reason" placeholder="Reason" value={reason} onChangeText={setReason}/>{['AVAILABLE','RETURNED'].includes(selected.status)?<><TextInput style={S.input} placeholder="Find an employee" value={employeeSearch} onChangeText={setEmployeeSearch}/>{employees.data?.filter(e=>e.name.toLowerCase().includes(employeeSearch.toLowerCase())).slice(0,10).map(e=><Pressable key={e.id} onPress={()=>setEmployee(e.id)}><Text style={S.body}>{employee===e.id?'✓ ':'○ '}{e.name}</Text></Pressable>)}<Pressable disabled={busy||!employee||!reason.trim()} style={S.btn} onPress={()=>void queue('asset_assignment',{asset_id:selected.id,employee_id:employee,condition,reason})}><Text style={S.btnText}>Assign to employee</Text></Pressable></>:null}{(edges[selected.status]??[]).map(status=><Pressable disabled={busy||!reason.trim()} key={status} style={S.btnGhost} onPress={()=>void queue('asset_transition',{asset_id:selected.id,status,condition,reason})}><Text style={S.btnGhostText}>{status.replaceAll('_',' ')}</Text></Pressable>)}</>:null}</Card>:null}
 <Modal visible={scanning} onRequestClose={()=>setScanning(false)}><View style={{flex:1}}><CameraView style={{flex:1}} barcodeScannerSettings={{barcodeTypes:['qr','code128','code39','ean13']}} onBarcodeScanned={({data})=>void scan(data)}/><Pressable style={S.btn} onPress={()=>setScanning(false)}><Text style={S.btnText}>Cancel scan</Text></Pressable></View></Modal><View style={{height:48}}/></ScrollView>;
}
