'use client';
import {useMemo,useState} from 'react';
import {useQueryClient} from '@tanstack/react-query';
import {parseCsv} from '@/lib/csv';
import {apiRequest} from '@/lib/apiClient';
import {Workbench,Panel,type Row} from '@/components/v2/Workbench';
import {RequirePermission} from '@/components/RequirePermission';
import {Button} from '@/components/ui/Button';
import {ErrorCard} from '@/components/ui/ErrorCard';
const template='type,code,name,parent_code\ndistrict,D1,Example district,\nmandal,M1,Example mandal,D1\nvillage,V1,Example village,M1\nsite,S1,Example site,V1\n';
export default function Page(){const [text,setText]=useState(''),[result,setResult]=useState<Row|null>(null),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false),client=useQueryClient();
 const rows=useMemo(()=>{const [headers,...data]=parseCsv(text);return headers?data.filter(r=>r.some(c=>c.trim())).map(row=>Object.fromEntries(headers.map((h,n)=>[h.trim().toLowerCase(),row[n]?.trim()??'']))):[];},[text]);
 async function submit(preview:boolean){setBusy(true);setError(undefined);try{const r=await apiRequest<Row>('/api/v1/org/units/import',{method:'POST',body:{rows,dry_run:preview}});setResult(r.data);if(!preview)await client.invalidateQueries();}catch(e){setError(e);}finally{setBusy(false);}}
 function update(value:string){setText(value);setResult(null);setError(undefined);}
 return <Workbench title="Import locations" description="Validate district, mandal, village and site records before importing. Parent codes can refer to another row in the same file."><RequirePermission code="org.units.manage"><Panel title="CSV staging"><input aria-label="Location CSV file" type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(file)update(await file.text());}}/><textarea aria-label="Location CSV" value={text} onChange={e=>update(e.target.value)} rows={10} className="my-4 w-full rounded border p-3 font-mono text-sm" placeholder={template}/><div className="flex flex-wrap gap-3"><Button variant="secondary" onClick={()=>update(template)}>Load sample template</Button><Button disabled={!rows.length||rows.length>500} loading={busy} onClick={()=>void submit(true)}>Validate {rows.length} rows</Button>{result?.dry_run?<Button disabled={!result.validated||busy} onClick={()=>void submit(false)}>Import {result.validated} validated rows</Button>:null}</div><p className="mt-3 text-sm text-text-muted">Up to 500 rows per batch. Duplicate codes retain the existing record; rejected rows show a reason.</p></Panel>{error?<ErrorCard error={error}/>:null}{result?<Panel title={result.dry_run?'Validation results':'Import results'}><p className="mb-3 text-sm">{result.validated} validated · {result.imported} imported · {result.duplicates} duplicates · {result.rejected} rejected</p><div className="max-h-96 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Row</th><th>Code</th><th>Result</th><th>Reason</th></tr></thead><tbody>{result.results.map((r:Row)=><tr key={r.row} className="border-t"><td className="py-2">{r.row}</td><td>{r.code??'—'}</td><td>{r.status}</td><td>{r.message??'—'}</td></tr>)}</tbody></table></div></Panel>:null}</RequirePermission></Workbench>;
}
