'use client';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {apiRequest} from '@/lib/apiClient';
import {Panel,Collection,MutationForm,Can,choices,type Row} from './Workbench';
import {ErrorCard} from '@/components/ui/ErrorCard';
import Link from '@/components/AppLink';
export function Advisories({project}:{project:string}){
 const [review,setReview]=useState<Row|null>(null),[skill,setSkill]=useState('');
 const workforce=useQuery({queryKey:['workforce',project,skill],queryFn:async()=>(await apiRequest<Row>(`/api/v1/insights/projects/${project}/workforce?skill=${encodeURIComponent(skill)}`)).data});
 return <><Panel title="Workforce recommendations"><label className="text-sm">Required skill (optional)<input className="ml-2 rounded border p-2" value={skill} maxLength={100} onChange={e=>setSkill(e.target.value)}/></label>{workforce.isLoading?<p className="mt-3">Loading capacity…</p>:null}{workforce.error?<ErrorCard error={workforce.error}/>:null}{workforce.data?<><p className="my-3 text-sm text-slate-600">{workforce.data.scope_note}</p>{!workforce.data.data.length?<p>Insufficient data: no eligible colleagues in your scope.</p>:workforce.data.data.map((r:Row)=><div key={r.id} className="border-b py-3 text-sm"><p className="font-medium">{r.username} · {r.visible_open_tasks} visible open tasks</p><p>{r.on_leave?'On leave':r.recommended_action}{r.skill_match===true?' · Skill matches':''}</p></div>)}<p className="mt-3 text-xs text-slate-500">{workforce.data.model_version} · {workforce.data.prediction_timestamp} · Rule-based guidance; statistical confidence unavailable.</p></>:null}</Panel><Panel title="Evidence review cases"><p className="mb-4 text-sm text-slate-600">An identical file on different tasks creates a review case. Reuse may be legitimate; a reviewer records the outcome.</p><Collection path={`insights/projects/${project}/reviews`} columns={[{key:'kind',label:'Signal'},{key:'status',label:'Review'},{key:'created_at',label:'Detected'}]} onSelect={setReview}/>{review?<div className="mt-4 space-y-3"><Link className="text-blue-700 underline" href={`/projects/${project}/tasks/${review.task_id}`}>Open task and evidence</Link><p className="text-sm">{review.factors.recommended_action}</p>{review.status==='OPEN'?<Can permission="project.update"><MutationForm key={review.id+review.version} path={`insights/reviews/${review.id}/decision`} version={review.version} fields={[{key:'status',label:'Outcome',type:'select',required:true,options:choices(['CONFIRMED','DISMISSED'])},{key:'reason',label:'Review reason',type:'textarea',required:true}]} submit="Record review" onSaved={setReview}/></Can>:<p className="text-sm">{review.reason} · {review.reviewed_at}</p>}</div>:null}</Panel></>;
}
