'use client';
import {useRows,type Row} from './Workbench';
export function Timeline({tasks,project,month,zoom,onSelect}:{tasks:Row[];project:string;month:string;zoom:string;onSelect:(t:Row)=>void}){
 const links=useRows(`projects/${project}/dependencies`),scale=zoom==='week'?35:zoom==='month'?18:6,base=new Date(`${month}-01`).getTime(),day=86400000;
 const x=(date:unknown)=>Math.max(0,(new Date(String(date)).getTime()-base)/day*scale),geometry=new Map(tasks.map((t,i)=>[t.id,{start:x(t.planned_start_date??t.created_at),end:x(t.planned_end_date??t.created_at),y:i*52+26}]));
 const edges=(links.data?.rows??[]).filter(d=>geometry.has(d.predecessor_id)&&geometry.has(d.successor_id));
 const width=Math.max(800,...Array.from(geometry.values(),r=>r.end+80));
 return <div className="overflow-x-auto"><div className="relative" style={{width:width+220,minHeight:tasks.length*52}}><svg className="pointer-events-none absolute left-[220px] top-0" width={width} height={tasks.length*52} aria-hidden="true"><defs><marker id="dependency-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10z" fill="#64748b"/></marker></defs>{edges.map((d,i)=>{const a=geometry.get(d.predecessor_id)!,b=geometry.get(d.successor_id)!;return <path key={i} d={`M${Math.max(a.end,a.start+30)} ${a.y} H${Math.max(a.end,a.start+30)+14} V${b.y} H${b.start}`} stroke="#64748b" strokeWidth="1.5" fill="none" markerEnd="url(#dependency-arrow)"/>;})}</svg>{tasks.map(t=>{const g=geometry.get(t.id)!,latePredecessor=edges.some(e=>e.successor_id===t.id&&tasks.some(p=>p.id===e.predecessor_id&&!['DONE','CANCELLED'].includes(p.status)&&p.planned_end_date&&p.planned_end_date<new Date().toISOString().slice(0,10)));return <div key={t.id} className="relative grid h-[52px] grid-cols-[220px_1fr] items-center border-b"><button className="truncate pr-3 text-left text-sm" onClick={()=>onSelect(t)} title={t.title}>{t.title}</button><div><button onClick={()=>onSelect(t)} title={`${t.planned_start_date??'Unscheduled'} → ${t.planned_end_date??'Unscheduled'}${latePredecessor?' · predecessor overdue':''}`} style={{marginLeft:g.start,width:Math.max(30,g.end-g.start)}} className={`h-7 rounded px-2 text-xs ${latePredecessor?'bg-amber-200 ring-2 ring-amber-600':'bg-blue-200'}`}>{t.status}</button></div></div>;})}</div>{edges.length?<ul className="mt-3 text-xs text-slate-600">{edges.map((e,i)=><li key={i}>{tasks.find(t=>t.id===e.predecessor_id)?.title} → {tasks.find(t=>t.id===e.successor_id)?.title}</li>)}</ul>:<p className="mt-3 text-xs text-slate-500">No dependencies in the displayed tasks.</p>}</div>;
}
