'use client';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiRequest} from '@/lib/apiClient';
import {Button} from '@/components/ui/Button';
import {ErrorCard} from '@/components/ui/ErrorCard';
import {type Row,MutationForm,useRows} from './Workbench';
export function WorkflowEditor({project}:{project:string}){
 const query=useQuery({queryKey:['workflow',project],queryFn:async()=>(await apiRequest<Row>(`/api/v1/projects/${project}/workflow`)).data});
 if(query.error)return <ErrorCard error={query.error}/>;if(!query.data)return <p>Loading workflow…</p>;
 return <WorkflowForm key={project+query.data.version} project={project} current={query.data}/>;
}
function WorkflowForm({project,current}:{project:string;current:Row}){
 const [statuses,setStatuses]=useState<string[]>(current.statuses),[edges,setEdges]=useState<Record<string,string[]>>(current.allowed_transitions),[name,setName]=useState(''),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false),client=useQueryClient();
 return <div className="space-y-4"><p className="text-sm text-text-muted">Choose each allowed next step. TO_DO starts new work; DONE and CANCELLED end it. Changes apply to this project.</p>{statuses.map(from=><fieldset key={from} className="rounded border p-3"><legend className="px-1 text-sm font-medium">{from}</legend>{['DONE','CANCELLED'].includes(from)?<span className="text-xs text-text-muted">Terminal status</span>:<div className="flex flex-wrap gap-4">{statuses.filter(to=>to!==from).map(to=><label key={to} className="text-sm"><input type="checkbox" className="mr-1" checked={(edges[from]??[]).includes(to)} onChange={e=>setEdges({...edges,[from]:e.target.checked?[...(edges[from]??[]),to]:(edges[from]??[]).filter(s=>s!==to)})}/>{to}</label>)}</div>}</fieldset>)}<div className="flex gap-2"><input aria-label="New status code" className="rounded border p-2" placeholder="e.g. QUALITY_CHECK" value={name} onChange={e=>setName(e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,''))} maxLength={20}/><Button variant="secondary" disabled={!/^[A-Z][A-Z0-9_]{0,19}$/.test(name)||statuses.includes(name)} onClick={()=>{setStatuses([...statuses,name]);setEdges({...edges,[name]:[]});setName('');}}>Add status</Button></div><Button loading={busy} onClick={async()=>{setBusy(true);setError(undefined);try{await apiRequest(`/api/v1/projects/${project}/workflow`,{method:'PUT',headers:{'If-Match':String(current.version)},body:{statuses,allowed_transitions:edges}});await client.invalidateQueries();}catch(e){setError(e);}finally{setBusy(false);}}}>Save workflow</Button>{error?<ErrorCard error={error}/>:null}</div>;
}
export function TaskCustomFields({task,planning}:{task:Row;planning:Row}){const defs=useRows(`custom-fields?project_id=${task.project_id}`);if(!defs.data?.rows.length)return null;return <MutationForm key={planning.version} path={`tasks/${task.id}/planning`} method="PATCH" version={planning.version} initial={planning.custom_fields} fields={defs.data.rows.map(d=>({key:d.field_key,label:d.name,required:d.required,type:d.field_type==='boolean'?'checkbox':d.field_type==='user'?'select':d.field_type,source:d.field_type==='user'?`projects/${task.project_id}/people`:undefined,options:d.field_type==='user'?undefined:d.options?.map((value:string)=>({value,label:value}))}))} transform={values=>({custom_fields:Object.fromEntries(Object.entries(values).map(([k,v])=>[k,defs.data?.rows.find(d=>d.field_key===k)?.field_type==='number'?Number(v):v]))})} submit="Save custom fields"/>;}
