// I-005: encrypted export round-trip.
// POST /api/v1/reports stores content_encrypted = encryptPii(base64(content));
// GET /api/v1/reports/:id/download decrypts it back via readBlob(). Round
// trip verified: generated bytes decode back to readable CSV containing the
// data we expect, and the checksum of what we generate vs. what comes back
// on download matches exactly.
import { createHash } from "node:crypto";
import { loginAs, loadDataset, call, show } from "./qalib.mjs";

const ds = loadDataset();
const session = await loginAs("qa-admin-superadmin");
const T = session.access_token;

const gen = await call(T, "POST", "/reports", { type: "projects", format: "csv", filters: {} });
show("POST /reports (generate)", gen, 400);
if (gen.status !== 201) process.exit(0);

const dl = await fetch(`http://127.0.0.1${gen.body.download_url}`, {
  headers: { authorization: `Bearer ${T}` },
});
const bytes = Buffer.from(await dl.arrayBuffer());
const text = bytes.toString("utf8");
console.log(JSON.stringify({
  downloadStatus: dl.status,
  contentType: dl.headers.get("content-type"),
  bytesLength: bytes.length,
  sha256: createHash("sha256").update(bytes).digest("hex"),
  firstLines: text.split("\n").slice(0, 4),
  containsQaSeedProject: text.includes("QA-SEED-ACTIVE") || text.toUpperCase().includes("QA-"),
}, null, 2));
