'use client';
import {useState} from 'react';
import {SlaPolicy} from '@/components/v2/SlaPolicy';
import {Timeline} from '@/components/v2/Timeline';
import {WorkflowEditor,TaskCustomFields} from '@/components/v2/WorkflowEditor';
import {TaskFilters} from '@/components/v2/TaskFilters';
import {listTasksPage,type ListTasksParams} from '@/lib/tasks';
import {useInfiniteQuery,useQuery,useQueryClient} from '@tanstack/react-query';
import Link from '@/components/AppLink';
import {apiRequest} from '@/lib/apiClient';
import {Workbench,Panel,Can,Collection,MutationForm,ProjectPicker,choices,useRows,type Row} from '@/components/v2/Workbench';
import {Button} from '@/components/ui/Button';
import {ErrorCard} from '@/components/ui/ErrorCard';
export default function Page(){
 const [project,setProject]=useState(''),[view,setView]=useState('Calendar'),[cycle,setCycle]=useState<Row|null>(null),[task,setTask]=useState<Row|null>(null),[error,setError]=useState<unknown>(),[zoom,setZoom]=useState('month'),client=useQueryClient();
 const [filters,setFilters]=useState<ListTasksParams>({});
 const taskPages=useInfiniteQuery({queryKey:['planning-tasks',project,filters],queryFn:({pageParam})=>listTasksPage({...filters,project_id:project,limit:100,cursor:pageParam}),initialPageParam:undefined as string|undefined,getNextPageParam:last=>last.has_more?last.next_cursor??undefined:undefined,enabled:!!project});
 const tasks={...taskPages,data:{rows:taskPages.data?.pages.flatMap(p=>p.tasks)??[],hasMore:taskPages.hasNextPage}};
 const cycles=useRows(`cycles?project_id=${project}&limit=100`,!!project);
 const [selected,setSelected]=useState<string[]>([]),[bulkStatus,setBulkStatus]=useState('IN_PROGRESS');
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7));
 const projectDetails=useQuery({queryKey:['planning-project',project],queryFn:async()=>(await apiRequest<Row>(`/api/v1/projects/${project}`)).data,enabled:!!project});
 const projectType=projectDetails.data?.project_type_id;
 const details=useQuery({queryKey:['planning',task?.id],queryFn:async()=>(await apiRequest<Row>(`/api/v1/tasks/${task!.id}/planning`)).data,enabled:!!task});
 async function moveTask(t:Row,date:string){try{await apiRequest(`/api/v1/tasks/${t.id}`,{method:'PATCH',headers:{'If-Match':String(t.version)},body:{planned_end_date:date}});await client.invalidateQueries();}catch(e){setError(e);}}
 const days=Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()},(_,n)=>`${month}-${String(n+1).padStart(2,'0')}`);
 return <Workbench title="Work planning" description="Plan iterations, schedule tasks, and track work across list, calendar, and timeline views."><ProjectPicker value={project} onChange={p=>{setProject(p);setFilters({});setTask(null);setCycle(null);setSelected([]);}}/>{error?<ErrorCard error={error}/>:null}{project?<>
 <div className="flex flex-wrap gap-2">{['Calendar','Timeline','List','Cycles','Custom fields','Workflow','SLA policy'].map(v=><Button key={v} variant={view===v?'primary':'secondary'} onClick={()=>setView(v)}>{v}</Button>)}</div>
 {['Calendar','Timeline','List'].includes(view)?<Panel title={view}>
 <div className="mb-5"><TaskFilters project={project} value={filters} onChange={setFilters}/></div>
 {view==='Calendar'?<><label className="mb-4 block text-sm">Month <input aria-label="Calendar month" type="month" value={month} onChange={e=>setMonth(e.target.value)} className="rounded border p-2"/></label><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{days.map(day=><div key={day} className="min-h-28 rounded border border-slate-200 bg-slate-50 p-2" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const t=tasks.data?.rows.find(t=>t.id===e.dataTransfer.getData('text/plain'));if(t)void moveTask(t,day);}}><span className="text-xs text-slate-500">{day}</span>{tasks.data?.rows.filter(t=>t.planned_end_date===day).map(t=><button key={t.id} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',t.id)} onClick={()=>setTask(t)} className="mt-2 block w-full rounded bg-blue-100 p-2 text-left text-xs text-blue-950">{t.title}</button>)}</div>)}</div></>:view==='Timeline'?<><label className="mb-3 block text-sm">Zoom <select value={zoom} onChange={e=>setZoom(e.target.value)} className="rounded border p-2">{['week','month','quarter'].map(z=><option key={z}>{z}</option>)}</select></label><Timeline tasks={tasks.data?.rows??[]} project={project} month={month} zoom={zoom} onSelect={setTask}/></>:<><Can permission="task.update"><div className="mb-4 flex gap-2"><select aria-label="Bulk status" className="rounded border p-2" value={bulkStatus} onChange={e=>setBulkStatus(e.target.value)}>{choices(['TO_DO','IN_PROGRESS','IN_REVIEW','DONE','BLOCKED','CANCELLED']).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><Button disabled={!selected.length} onClick={async()=>{try{const {data}=await apiRequest<Row>('/api/v1/tasks/bulk',{method:'POST',body:{tasks:tasks.data?.rows.filter(t=>selected.includes(t.id)).map(t=>({id:t.id,version:t.version})),action:'status',value:bulkStatus}});const failed=data.data.filter((r:Row)=>r.status>=400);if(failed.length)throw new Error(`${failed.length} task changes were rejected. Reload and review their workflow or permissions.`);setSelected([]);await client.invalidateQueries();}catch(e){setError(e);}}}>Update {selected.length} selected</Button></div></Can>{tasks.data?.rows.map(t=><div key={t.id} className="flex items-center gap-3 border-b py-3"><input type="checkbox" aria-label={`Select ${t.title}`} checked={selected.includes(t.id)} onChange={e=>setSelected(e.target.checked?[...selected,t.id]:selected.filter(id=>id!==t.id))}/><Link className="flex-1 text-sm font-medium text-blue-700" href={`/projects/${project}/tasks/${t.id}`}>{t.title}</Link><span className="text-xs">{t.status}</span><Button variant="secondary" onClick={()=>setTask(t)}>Plan</Button></div>)}</>}
 {tasks.isLoading?<p>Loading tasks…</p>:null}{tasks.error?<ErrorCard error={tasks.error}/>:null}{tasks.data?.hasMore?<Button variant="secondary" loading={taskPages.isFetchingNextPage} onClick={()=>void taskPages.fetchNextPage()}>Load more tasks ({tasks.data.rows.length} shown)</Button>:null}</Panel>:null}
 {view==='Cycles'?<><Panel title="Iterations"><Collection path={`cycles?project_id=${project}`} columns={[{key:'name',label:'Name'},{key:'start_date',label:'Start'},{key:'end_date',label:'End'},{key:'status',label:'Status'}]} onSelect={setCycle}/></Panel><Can permission="cycle.manage"><Panel title="New cycle"><MutationForm path="cycles" key={project} transform={v=>({...v,project_id:project})} fields={[{key:'name',label:'Name',required:true},{key:'start_date',label:'Start',type:'date',required:true},{key:'end_date',label:'End',type:'date',required:true},{key:'goal',label:'Goal'},{key:'rollover',label:'Unfinished work',type:'select',options:[{value:'NEXT',label:'Move to next cycle'},{value:'BACKLOG',label:'Return to backlog'}],default:'NEXT'}]}/></Panel>{cycle&&cycle.status!=='CLOSED'?<Panel title={`${cycle.name} · ${cycle.status}`}><MutationForm key={cycle.id+cycle.version} path={`cycles/${cycle.id}/${cycle.status==='PLANNED'?'start':'close'}`} version={cycle.version} fields={[]} submit={cycle.status==='PLANNED'?'Start cycle':'Close and roll unfinished work'} onSaved={setCycle}/></Panel>:null}</Can></>:null}
 {view==='SLA policy'?<Can permission="project.update"><Panel title="Deadline thresholds and escalation"><SlaPolicy project={project}/></Panel></Can>:null}
 {view==='Workflow'?<Can permission="board.manage"><Panel title="Project workflow"><WorkflowEditor project={project}/></Panel></Can>:null}
 {view==='Custom fields'?<><Panel title="Project fields"><Collection path={`custom-fields?project_id=${project}`} columns={[{key:'name',label:'Name'},{key:'field_key',label:'Key'},{key:'field_type',label:'Type'},{key:'required',label:'Required'}]}/></Panel><Can permission="custom_field.manage"><Panel title="Define field"><MutationForm path="custom-fields" key={project} transform={v=>{const {apply_to_type,...values}=v;return {...values,...(apply_to_type&&projectType?{project_type_id:projectType}:{project_id:project}),options:String(v.options??'').split(',').map(s=>s.trim()).filter(Boolean)};}} fields={[{key:'name',label:'Field name',required:true},{key:'field_key',label:'Unique key',required:true},{key:'field_type',label:'Type',type:'select',options:choices(['text','number','date','select','multi_select','user','boolean']),required:true},{key:'options',label:'Choices (comma separated)'},{key:'required',label:'Required',type:'checkbox'},...(projectType?[{key:'apply_to_type',label:'Define for every project of this type',type:'checkbox' as const}]:[])]}/></Panel></Can></>:null}
 {task&&details.data?<Panel title={`Plan ${task.title}`}><MutationForm key={task.id+details.data.version} path={`tasks/${task.id}/planning`} method="PATCH" version={details.data.version} initial={details.data} fields={[{key:'cycle_id',label:'Cycle',type:'select',options:cycles.data?.rows.filter(c=>c.status!=='CLOSED').map(c=>({value:c.id,label:c.name}))}]} transform={v=>({cycle_id:v.cycle_id??null})}/><div className="mt-5"><TaskChecklist task={task} planning={details.data}/><div className="mt-5"><TaskCustomFields task={task} planning={details.data}/></div></div><div className="mt-5"><MutationForm path={`tasks/${task.id}`} method="PATCH" version={details.data.version} initial={task} fields={[{key:'planned_start_date',label:'Start date',type:'date'},{key:'planned_end_date',label:'Due date',type:'date'}]} submit="Reschedule"/></div></Panel>:null}
 </>:<Panel title="Choose a project"><p className="text-slate-500">Select a project to open its planning views.</p></Panel>}</Workbench>;
}
function TaskChecklist({task,planning}:{task:Row;planning:Row}){const [title,setTitle]=useState(''),[error,setError]=useState<unknown>(),client=useQueryClient();async function save(checklist:Row[]){try{await apiRequest(`/api/v1/tasks/${task.id}/planning`,{method:'PATCH',headers:{'If-Match':String(planning.version)},body:{checklist}});await client.invalidateQueries();}catch(e){setError(e);}}
 return <div><h3 className="mb-3 font-medium">Checklist</h3>{planning.checklist.map((c:Row)=><label key={c.id} className="my-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={c.done} onChange={e=>void save(planning.checklist.map((x:Row)=>x.id===c.id?{...x,done:e.target.checked}:x))}/>{c.title}</label>)}<form className="flex gap-2" onSubmit={e=>{e.preventDefault();if(title.trim()){void save([...planning.checklist,{id:crypto.randomUUID(),title:title.trim(),done:false}]);setTitle('');}}}><input aria-label="Checklist item" className="rounded border p-2" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Add checklist item"/><Button type="submit" variant="secondary">Add</Button></form>{error?<ErrorCard error={error}/>:null}</div>;
}
