'use client';
import {useState} from 'react';
import {ReportForm} from '@/components/ReportForm';
import {Workbench,Panel,Collection,MutationForm,choices,type Row} from '@/components/v2/Workbench';
import {RequirePermission} from '@/components/RequirePermission';
import {DownloadButton} from '@/components/DownloadButton';
import {REPORT_TYPE_META} from '@/lib/reports';
import {useAuth} from '@/components/AuthProvider';
export default function ReportsPage(){const [schedule,setSchedule]=useState<Row|null>(null),[report,setReport]=useState<Row|null>(null),{session}=useAuth();return <Workbench title="Reports" description="Generate scoped exports, download previous results, and schedule recurring reports."><RequirePermission code="report.generate"><ReportForm/><Panel title="Your reports"><Collection path="reports" columns={[{key:'type',label:'Report'},{key:'format',label:'Format'},{key:'rows',label:'Rows'},{key:'status',label:'Status'},{key:'error',label:'Error'},{key:'created_at',label:'Generated'}]} onSelect={setReport}/>{report?.status==='READY'?<DownloadButton path={report.download_url} name={`report-${report.id}.${report.format}`} label="Download selected report"/>:null}</Panel><Panel title="Recurring reports"><Collection path="report-schedules" columns={[{key:'name',label:'Name'},{key:'frequency',label:'Frequency'},{key:'next_run_at',label:'Next run'},{key:'active',label:'Enabled'},{key:'error',label:'Last error'}]} onSelect={setSchedule}/></Panel><Panel title="Schedule a report"><p className="mb-4 text-sm text-slate-500">The first report runs shortly. Later reports run at this time each day, week, or month. Results appear here and in your inbox.</p><MutationForm path="report-schedules" fields={[{key:'name',label:'Name',required:true},{key:'type',label:'Report type',type:'select',required:true,options:REPORT_TYPE_META.filter(t=>session?.permissions.includes(t.permission)).map(t=>({value:t.type,label:t.label}))},{key:'format',label:'Format',type:'select',options:choices(['csv','xlsx','pdf']),default:'xlsx'},{key:'frequency',label:'Frequency',type:'select',options:choices(['DAILY','WEEKLY','MONTHLY']),default:'WEEKLY'}]}/></Panel>{schedule?<Panel title={schedule.name}><MutationForm key={schedule.id+schedule.version} path={`report-schedules/${schedule.id}`} method="PATCH" version={schedule.version} initial={schedule} fields={[{key:'active',label:'Enabled',type:'checkbox'}]} onSaved={setSchedule}/></Panel>:null}</RequirePermission></Workbench>;}
