'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {useAuth} from './AuthProvider';
import {useRows,MutationForm,ProjectPicker,type Row} from './v2/Workbench';
import {staticHref} from '@/lib/routes';
import {ErrorCard} from './ui/ErrorCard';
export function CommandPalette(){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[create,setCreate]=useState(false),[project,setProject]=useState(''),box=useRef<HTMLDivElement>(null),router=useRouter(),{session}=useAuth();
 const results=useRows(`search?q=${encodeURIComponent(search)}`,open&&search.length>=2);
 useEffect(()=>{const t=setTimeout(()=>setSearch(query.trim()),250);return ()=>clearTimeout(t);},[query]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(v=>!v);}if(e.key==='Escape')setOpen(false);};document.addEventListener('keydown',key);return ()=>document.removeEventListener('keydown',key);},[]);
 useEffect(()=>{if(open)box.current?.querySelector<HTMLInputElement>('input')?.focus();},[open,create]);
 const go=(path:string)=>{router.push(staticHref(path));setOpen(false);setQuery('');};
 const path=(r:Row)=>r.type==='task'?`/projects/${r.project_id}/tasks/${r.id}`:r.type==='employee'?`/employees/${r.id}`:`/projects/${r.id}`;
 return <><button type="button" className="rounded border border-slate-200 px-3 py-1.5 text-sm text-slate-500" onClick={()=>{setCreate(false);setOpen(true);}} aria-label="Open search and commands">Search <kbd className="ml-3 hidden text-xs sm:inline">⌘ / Ctrl K</kbd></button>{open?<div className="fixed inset-0 z-50 flex items-start justify-center bg-slate-950/40 px-4 pt-[12vh]" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false);}}><div ref={box} role="dialog" aria-modal="true" aria-label="Search and commands" className="max-h-[75vh] w-full max-w-xl overflow-y-auto rounded-xl bg-white p-5 shadow-xl" onKeyDown={e=>{if(e.key==='Tab'){const nodes=box.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,a');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><div className="mb-3 flex justify-between"><h2 className="font-semibold">{create?'Create task':'Search and commands'}</h2><button onClick={()=>setOpen(false)} aria-label="Close commands">Esc · Close</button></div>{create?<><ProjectPicker value={project} onChange={setProject}/>{project?<div className="mt-4"><MutationForm path="tasks" fields={[{key:'title',label:'Task title',required:true}]} transform={v=>({...v,project_id:project})} onSaved={r=>go(`/projects/${project}/tasks/${r.id}`)} submit="Create task"/></div>:null}</>:<><input aria-label="Search projects, tasks, employees" placeholder="Search projects, tasks, employees…" className="w-full rounded border p-3" value={query} onChange={e=>setQuery(e.target.value)}/><div className="my-3 grid gap-1">{[['My work','/my-work'],['Projects','/projects'],['Dashboard','/dashboard']].map(([title,path])=><button key={path} className="rounded px-3 py-2 text-left text-sm hover:bg-slate-100" onClick={()=>go(path)}>{title}</button>)}{session?.permissions.includes('task.create')?<button className="rounded px-3 py-2 text-left text-sm hover:bg-slate-100" onClick={()=>setCreate(true)}>Create task…</button>:null}</div>{results.isLoading&&search.length>=2?<p className="text-sm text-slate-500">Searching…</p>:null}{results.error?<ErrorCard error={results.error}/>:null}{results.data?.rows.map(r=><button key={r.type+r.id} className="block w-full border-t px-3 py-3 text-left text-sm hover:bg-slate-50" onClick={()=>go(path(r))}><span className="mr-3 text-xs uppercase text-slate-400">{r.type}</span>{r.title}</button>)}{search.length>=2&&results.data?.rows.length===0?<p className="text-sm text-slate-500">No matching records in your scope.</p>:null}</>}</div></div>:null}</>;
}
