'use client';
import {useState} from 'react';
import {useReveal} from '@/lib/use-reveal';
import {useAuth} from '@/components/AuthProvider';
import {apiRequest} from '@/lib/apiClient';
import {Workbench,Panel,Collection,MutationForm,type Row} from '@/components/v2/Workbench';
import {Button} from '@/components/ui/Button';
import {ErrorCard} from '@/components/ui/ErrorCard';
export default function Page(){const {session,refetchSession}=useAuth(),[setup,setSetup]=useState<Row|null>(null),[selected,setSelected]=useState<Row|null>(null),sessionRef=useReveal(selected?String(selected.id):null),[error,setError]=useState<unknown>();return <Workbench title="Account security" description="Set up an authenticator and review the sessions that can access your account."><Panel title="Two-factor authentication"><p className="mb-4">{session?.user.mfa_enabled?'Authenticator enabled.':'Authenticator is not enabled.'}</p>{!session?.user.mfa_enabled?<Button onClick={async()=>{try{setSetup((await apiRequest<Row>('/api/v1/auth/mfa/setup',{method:'POST',body:{}})).data);}catch(e){setError(e);}}}>Set up authenticator</Button>:null}{setup?<div className="mt-4 space-y-4"><p className="text-sm">Enter this key in your authenticator app, then confirm a six-digit code.</p><code className="block break-all rounded bg-surface-sunken p-3">{setup.secret}</code><MutationForm path="auth/mfa/verify" fields={[{key:'code',label:'Authentication code',required:true}]} submit="Verify and enable" onSaved={()=>{setSetup(null);void refetchSession();}}/></div>:null}{error?<ErrorCard error={error}/>:null}</Panel><Panel title="Your password"><p className="mb-1 text-sm text-text-muted">Changing it signs you out everywhere, this browser included.</p><p className="mb-4 text-sm text-text-muted">{session?.user.must_change_password?'This password was set by somebody else, so somebody else knows it. Set your own before continuing.':'Use at least 12 characters.'}</p><MutationForm path="auth/password" fields={[{key:'current_password',label:'Current password',type:'password',required:true},{key:'new_password',label:'New password',type:'password',required:true}]} submit="Change password" onSaved={()=>{window.location.href='/login';}}/></Panel><Panel title="Active sessions"><Collection path="auth/sessions" columns={[{key:'device',label:'Device'},{key:'ip',label:'IP address'},{key:'created_at',label:'Started'},{key:'last_used_at',label:'Last used'}]} onSelect={setSelected}/><div ref={sessionRef} className="scroll-mt-4"/>{selected?<MutationForm path={`auth/sessions/${selected.id}/revoke`} fields={[]} submit="Revoke selected session" onSaved={()=>setSelected(null)}/>:null}</Panel></Workbench>;}
